### ISSUE TITLE
2-5 Wardrobe Doors Should Be Shut Unless Triggered

### ISSUE THREAD

**Issue by wormyg** [EarlyWormGames/SkedaddleBugs#88] opened 2018-05-12 06:58 UTC
**Location:** Level number (2-5)
**Reproducibility:** Always
**Blocks gameplay:** No
**Version (if known):** Engine (12/05/2018)
**Priority:** 4(Low)
**Trello:** https://trello.com/c/alygZkQI/165-issue-88-p4

![2-5 locked cupboard should be shut](https://user-images.githubusercontent.com/37357402/39954578-7d8a4cde-5605-11e8-8a78-17b94f36b2f0.gif)

**Comment by LachlanRMMorrow** [comment] 2018-05-14 23:44
Closing as this is a duplicate of an existing bug.

**Closed as completed by LachlanRMMorrow** 2018-05-14 23:44 UTC
Labels: bug, programming, design/level design
